
FROM python:3.9


WORKDIR /code


COPY ./requirements.txt /code/requirements.txt


RUN pip install --upgrade pip && pip install --no-cache-dir --upgrade -r /code/requirements.txt


COPY ./app /code/app


COPY ./tests /code/tests


CMD ["uvicorn", "app.api:app", "--host", "0.0.0.0", "--port", "80"]

